### ISSUE TITLE
Access Group FrontEnd

### ISSUE THREAD

**Issue by iAGONY** [cosmotechintl/CosmoMarket-VendorPanel-Frontend#2]
As a system admin i must be able to create/update/view report/view details an access group so that I can assign roles to the sub users for both admin and vendors.

**Comment by samir515** [comment]
![Image](https://github.com/cosmotechintl/CosmoMarket-VendorPanel-Frontend/assets/165052452/09199fda-6e4e-4e0d-a423-38045155ce68)



![Image](https://github.com/cosmotechintl/CosmoMarket-VendorPanel-Frontend/assets/165052452/f3293ed3-b8f4-4823-8d04-b2febf00dcd7)



![Image](https://github.com/cosmotechintl/CosmoMarket-VendorPanel-Frontend/assets/165052452/7d934241-16e4-4d9b-b598-30d8fa9a9549)
